# .github/workflows/push.yml
name: "Validate Nix Files"

on:
  push:

jobs:
  parse:
    name: Parse
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run nix-instantiate
        run: |
          set -euo pipefail

          failures=0

          for cfg in $(git ls-files '*.nix'); do
            if nix-instantiate --parse $cfg > /dev/null; then
              echo "  ✓ $cfg"
            else
              echo "  ✗ $cfg"
              failures=$((failures+1))
            fi
          done

          if [ "$failures" -ne 0 ]; then
            echo -e "\n❌ $failures files failed parsing."
            exit 1
          else
            echo -e "\n✅ All files parsed successfully!"
          fi

  build:
    name: Build
    needs: [ parse ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run nix-instantiate
        run: |
          set -euo pipefail

          failures=0

          for cfg in $(git ls-files '*/devices/*.nix'); do
            echo -e "\n→ Building $cfg"

            if nix-instantiate --eval \
                -I nixpkgs=channel:nixos-unstable \
                -E "(
                  import <nixpkgs/nixos> {
                    configuration = {
                      imports            = [ ./${cfg} ];
                      system.stateVersion = \"23.05\";
                      fileSystems.\"/\" = {
                        device = \"/\";
                        fsType = \"tmpfs\";
                      };
                    };
                  }
                ).system" \
                >/dev/null
            then
              echo "  ✓ $cfg"
            else
              echo "  ✗ $cfg"
              failures=$((failures+1))
            fi
          done

          if [ "$failures" -ne 0 ]; then
            echo -e "\n❌ $failures device config(s) failed validation."
            exit 1
          else
            echo -e "\n✅ All device configs passed!"
          fi
