# .github/workflows/lint.yml
name: "Lint Nix Files"

on:
  push:
    paths:
      - '**/*.nix'
      - '.github/workflows/**'

jobs:
  lint:
    name: Lint (optional)
    # don't run on main unless it's the formatting commit
    if: |
      github.ref != 'refs/heads/main' ||
      github.event.head_commit.author.email == 'github-actions@github.com'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run nixfmt --check
        run: |
          set -euo pipefail

          failures=0

          for cfg in $(git ls-files '*.nix'); do
            if nix run nixpkgs#nixfmt-rfc-style -- --check --indent=4 $cfg >/dev/null 2>/dev/null; then
              echo "  ✓ $cfg"
            else
              echo "  ✗ $cfg"
              failures=$((failures+1))
            fi
          done

          if [ "$failures" -ne 0 ]; then
            echo -e "\n❌ $failures files failed linting."
            exit 1
          else
            echo -e "\n✅ All files passed linting!"
          fi
