# .github/workflows/lint.yml
name: "Lint Nix Files"

on:
  push:

jobs:
  nixfmt:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # 3. Find all .nix files and run nixfmt --check on them
      - name: Run nixfmt --check
        run: |
          # gather all tracked .nix files
          files=$(git ls-files '*.nix')

          if [ -z "$files" ]; then
            echo "No .nix files to check."
            exit 0
          fi

          # run the formatter in check mode; non-zero = failure
          nix run nixpkgs#nixfmt-rfc-style -- --check --indent=4 $files
