# .github/workflows/push-to-main.yml
name: "Validate Nix Files"

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0        # needed to detect changes against history
          persist-credentials: true

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run nixfmt
        run: |
          set -euo pipefail

          failures=0

          for cfg in $(git ls-files '*.nix'); do
            if nix run nixpkgs#nixfmt-rfc-style -- --indent=4 $cfg >/dev/null 2>/dev/null; then
              echo "  ✓ $cfg"
            else
              echo "  ✗ $cfg"
              failures=$((failures+1))
            fi
          done

          if [ "$failures" -ne 0 ]; then
            echo -e "\n❌ Formatting failed for $failures files."
            exit 1
          else
            echo -e "\n✅ All files formatted successfully!"
          fi

      - name: Commit formatting changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "✅ No formatting changes"
            exit 0
          fi
          git commit -m "chore: apply formatting"

      - name: Push formatting commit (safe!)
        run: |
          git push --force-with-lease origin main \
            || { echo "⚠️ Detected new commits on main – aborting push."; exit 0; }

  parse:
    name: Parse
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run nix-instantiate
        run: |
          set -euo pipefail

          failures=0

          for cfg in $(git ls-files '*.nix'); do
            if nix-instantiate --parse $cfg > /dev/null; then
              echo "  ✓ $cfg"
            else
              echo "  ✗ $cfg"
              failures=$((failures+1))
            fi
          done

          if [ "$failures" -ne 0 ]; then
            echo -e "\n❌ $failures files failed parsing."
            exit 1
          else
            echo -e "\n✅ All files parsed successfully!"
          fi

  build:
    name: Build
    needs: [ parse ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run nix-instantiate
        run: |
          set -euo pipefail

          failures=0

          for cfg in $(git ls-files '*/devices/*.nix'); do
            echo -e "\n→ Building $cfg"

            if nix-instantiate --eval \
                -I nixpkgs=channel:nixos-unstable \
                -E "(
                  import <nixpkgs/nixos> {
                    configuration = {
                      imports            = [ ./${cfg} ];
                      system.stateVersion = \"23.05\";
                      fileSystems.\"/\" = {
                        device = \"/\";
                        fsType = \"tmpfs\";
                      };
                    };
                  }
                ).system" \
                >/dev/null
            then
              echo "  ✓ $cfg"
            else
              echo "  ✗ $cfg"
              failures=$((failures+1))
            fi
          done

          if [ "$failures" -ne 0 ]; then
            echo -e "\n❌ $failures device config(s) failed validation."
            exit 1
          else
            echo -e "\n✅ All device configs passed!"
          fi
